test: add attack-chains detection test
armosec/system-tests pull request #162
Opened 2023-08-28 08:06 UTC by alegrey91

2023-08-31 19:42 UTC, kooomix requested changes

2023-08-31 19:42 UTC, kooomix commented on configurations/helm-proxy/httpd.conf
> +ServerName httpd-proxy.default:80
Why this change? (the dependant tests worked)

2023-08-31 19:42 UTC, kooomix commented on configurations/helm-proxy/san_scr.cnf
> +DNS.1 = httpd-proxy.default:80
Why these changes?

2023-08-31 19:42 UTC, kooomix commented on readme.md
> +| `test_scenario=value`    | test one of the available attack chain scenarios (located under `configurations/attack_chain_expected_values/`. <br>more info here: [https://github.com/armosec/attack-cha
I think it would be better to support chosing the scenario on the test configuration level (self.test_obj) rather than kwargs.
This will give us the flexibility to use just the test name as input for the list of tests.

2023-08-31 19:42 UTC, kooomix commented on tests_scripts/helm/ks_microservice.py
> +        #old_report_guid = self.get_report_guid(cluster_name=self.kubernetes_obj.get_cluster_name(), wait_to_result=True)
remove

2023-08-31 19:42 UTC, kooomix commented on tests_scripts/helm/ks_microservice.py
> +        while time.time() - start_time < timeout:
There is already a generic function that handles requests and timeouts, please use it instead to avoid duplication of logic.
(`def wait_for_report(report_type, timeout=120, sleep_interval=30, ignore_agent: bool = False, **kwargs):`)

2023-08-31 20:27 UTC, alegrey91 commented
> @alegrey91 Where in the code are you deploying the initial setup of the cluster for the given scenario?

You have to do it manually

2023-09-01 04:32 UTC, kooomix commented
> > @alegrey91 Where in the code are you deploying the initial setup of the cluster for the given scenario?
> 
> You have to do it manually

Is this is a temporary thing? Because we will have to the the tests itself also build up the configurations.

2023-09-01 08:00 UTC, alegrey91 commented
> > > @alegrey91 Where in the code are you deploying the initial setup of the cluster for the given scenario?
> > 
> > 
> > You have to do it manually
> 
> Is this is a temporary thing? Because we will have to the the tests itself also build up the configurations.

I would keep it separated. I would avoid mixing configurations and tests together. Each step of the pipeline should have its proper separation of duties.
Additionally, I didn't find a way to apply manifests with different priorities (eg. CRD for the IngressController should be installed before applying the Ingress resource).

2023-09-01 09:09 UTC, alegrey91 commented on tests_scripts/helm/ks_microservice.py
> +        while time.time() - start_time < timeout:
thanks for the suggestion! I modified the code according to your advice.

2023-09-01 09:13 UTC, alegrey91 commented on readme.md
> +| `test_scenario=value`    | test one of the available attack chain scenarios (located under `configurations/attack_chain_expected_values/`. <br>more info here: [https://github.com/armosec/attack-cha
Do you mean we should create a test for each test scenario?

2023-09-01 09:16 UTC, alegrey91 commented on configurations/helm-proxy/san_scr.cnf
> +DNS.1 = httpd-proxy.default:80
These changes are not needed. I'm going to remove them.

2023-09-01 09:16 UTC, alegrey91 commented on configurations/helm-proxy/httpd.conf
> +ServerName httpd-proxy.default:80
These changes are not needed. I'm going to remove them.

2023-09-01 12:26 UTC, kooomix commented
> > > > @alegrey91 Where in the code are you deploying the initial setup of the cluster for the given scenario?
> > > 
> > > 
> > > You have to do it manually
> > 
> > Is this is a temporary thing? Because we will have to the the tests itself also build up the configurations.
> 
> I would keep it separated. I would avoid mixing configurations and tests together. Each step of the pipeline should have its proper separation of duties.
> Additionally, I didn't find a way to apply manifests with different priorities (eg. CRD for the IngressController should be installed before applying the Ingress resource).

Unless you had something specific in mind, we can't integrate it within the main pipeline as it is built in a way the tests are automatic and doesn't  require any manual interference.
I also don't think it make sense to start messing around with keeping pre configured images or something for each test.

Applying different manifests is being used widely in our tests. If one dependant on another, you can just wait for confirmation the first one is live before deoying the next one.

2023-09-03 07:44 UTC, yuleib commented
@alegrey91 - Alessio tests are fully automated. We must fix the initial configuration for the cluster to be automated. If i selected (automatically supposed to be parameter which we are configuring) Test case 1 automatlly you should load to the cluster scenario 1, apply changes and start the test. 
We must fix that ASAP

2023-09-03 08:11 UTC, yuleib requested changes

2023-09-03 08:11 UTC, yuleib commented on tests_scripts/helm/ks_microservice.py
> +                    time.sleep(10)
please add log for any sleep time in the code so we will have indication that test is sleeping

2023-09-03 08:11 UTC, yuleib commented on tests_scripts/helm/ks_microservice.py
> +            if response['response']['attackChainsLastScan']:
i don't understand why we need this code block. You are not perfoning any action or updates here, 
you can leave the check for "  if response['total']['value'] != 0:" alone with timesleep. 
If after the overall time sleep we didn;t found any A.Cs return false.

2023-09-03 08:11 UTC, yuleib commented on tests_scripts/helm/ks_microservice.py
> +                break
i don;t like break points i nthe code, this is not good practice. See my above comment

2023-09-04 06:43 UTC, alegrey91 commented on configurations/attack_chains_expected_values/attack-chain-1.1.json
> +       "frameworkName":"security"
This is an example response taken from the BE

2023-09-04 06:48 UTC, alegrey91 commented on infrastructure/backend_api.py
> +            raise Exception("no attack-chains detected yet")
this is because the function `get_attack_chians` is used into the other function: [`wait_for_report`](https://github.com/armosec/system-tests/pull/162/files#diff-87d918802c9bc70e9af861f91b5d631f022c697efb2f1091ffec0c7dca5a94acL233).
The function handles exception in this line: https://github.com/armosec/system-tests/pull/162/files#diff-87d918802c9bc70e9af861f91b5d631f022c697efb2f1091ffec0c7dca5a94acL240

2023-09-04 06:49 UTC, alegrey91 commented on infrastructure/backend_api.py
> +            raise Exception(
same as above

2023-09-04 06:49 UTC, alegrey91 commented on tests_scripts/helm/ks_microservice.py
> +            test_scenario = self.test_driver.kwargs.get("test_scenario", "attack-chain-1.1")
ok

2023-09-04 06:49 UTC, alegrey91 commented on tests_scripts/helm/ks_microservice.py
> +    def poll_for_attack_chains(self, timeout=600):
I'm going to decrease to 300

2023-09-04 07:29 UTC, alegrey91 commented on tests_scripts/helm/ks_microservice.py
> +            if response['response']['attackChainsLastScan']:
this function is no longer needed. I'm going to remove it.

2023-09-04 15:33 UTC, kooomix requested changes

2023-09-04 15:33 UTC, kooomix commented on tests_scripts/helm/ks_microservice.py
> +                                           )
Did you get attack chains after 300 secs? I think we should increase it as vul sometime takes more than 5 minutes to be updated on DB.

2023-09-04 15:59 UTC, alegrey91 commented on tests_scripts/helm/ks_microservice.py
> +                                           )
restoring it to `600`

2023-09-04 19:23 UTC, yuleib commented
/describe

2023-09-04 19:29 UTC, yuleib approved these changes

2023-09-05 11:21 UTC, merged