CVE summaries system test implementation
armosec/system-tests pull request #166
Opened 2023-09-03 23:48 UTC by rcohencyberarmor

2023-09-04 07:48 UTC, Daniel-GrunbergerCA requested changes

2023-09-04 07:48 UTC, Daniel-GrunbergerCA commented on tests_scripts/kubernetes/base_k8s.py
> +    def get_CVEs_summaries_from_storage(self, CVEsSummariesKeys, namespace):
```suggestion
    def get_CVEs_summaries_from_storage(self, CVEs_summaries_keys, namespace):
```

2023-09-04 07:48 UTC, Daniel-GrunbergerCA commented on tests_scripts/kubernetes/base_k8s.py
> +        CVEsSummaries = []
```suggestion
        CVEs_summaries = []
```

2023-09-04 07:48 UTC, Daniel-GrunbergerCA commented on tests_scripts/kubernetes/base_k8s.py
> +        if any(isinstance(i, list) for i in CVEsSummariesKeys):
why do we need this if? From your implementation of `get_CVEs_summaries_keys` it looks like you know the value being returned?

2023-09-04 07:48 UTC, Daniel-GrunbergerCA commented on tests_scripts/kubernetes/base_k8s.py
> +            for keys in CVEsSummariesKeys:
let's follow python convention and use pascal case

2023-09-04 07:48 UTC, Daniel-GrunbergerCA commented on tests_scripts/kubernetes/base_k8s.py
> +    def get_CVEs_summaries_by_namespace_from_storage(self, CVEsSummariesKeys):
this name is a bit confusing. If the function "knows" that the keys are actually namespace names, so lets receive a parameter named `namespaces`. If you want to abstract away this detail from the function and call the parameter `CVEsSummariesKeys`, so let's not have  "by_namespace" on the name.
IMO it should be called `get_CVEs_summaries_by_scope_from_storage`, and the scope is decided as part of the key generation

2023-09-04 07:48 UTC, Daniel-GrunbergerCA commented on tests_scripts/kubernetes/base_k8s.py
> +        if any(isinstance(i, list) for i in CVEsSummariesKeys):
again, why do we need this if?

2023-09-04 07:48 UTC, Daniel-GrunbergerCA commented on tests_scripts/helm/base_vulnerability_scanning.py
> +    def validate_expected_CVEs_summaries(self, CVEs_summaries, expected_CVEs_summaries_path):
let's not receive a file path on the function. It should receive summaries and expected summaries and compare them. Reading from files it's not the responsibility of this function

2023-09-04 07:48 UTC, Daniel-GrunbergerCA commented on tests_scripts/helm/base_vulnerability_scanning.py
> +                    self.store_summary_data_for_first_time_results(result=CVE_summary, store_path=expected_CVE_summary)
what is this? why is it necessary? please add comments

2023-09-04 07:48 UTC, Daniel-GrunbergerCA commented on tests_scripts/helm/base_vulnerability_scanning.py
> +    def validate_expected_namespace_CVEs_summaries(self, CVEs_summaries, expected_CVEs_summaries_path, namespace):
same as above

2023-09-04 07:48 UTC, Daniel-GrunbergerCA commented on tests_scripts/helm/base_vulnerability_scanning.py
> +                    self.store_namespace_summary_data_for_first_time_results(result=CVE_summary, store_path=expected_CVE_summary, namespace=namespace)
same as above

2023-09-04 07:48 UTC, Daniel-GrunbergerCA commented on tests_scripts/helm/base_vulnerability_scanning.py
> +                    break
aren't we supposed to compare `vulnerabilitiesRef` as well?

2023-09-04 07:48 UTC, Daniel-GrunbergerCA commented on tests_scripts/helm/base_vulnerability_scanning.py
> +                Logger.logger.info("CVE_summary[1]['metadata']['name']: {} =?= expected_CVE_data['metadata']['name']: {}".format(CVE_summary[1]['metadata']['name'], expected_CVE_data['metadata']['nam
please remove this / write a more readable log

2023-09-04 07:48 UTC, Daniel-GrunbergerCA commented on tests_scripts/helm/relevant_cve.py
> +        # 3.9 test CVES summaries created as expected result in the storage
please add info logs as we have in other tests

2023-09-04 14:07 UTC, rcohencyberarmor commented on tests_scripts/kubernetes/base_k8s.py
> +        if any(isinstance(i, list) for i in CVEsSummariesKeys):
same as above

2023-09-04 14:12 UTC, rcohencyberarmor commented on tests_scripts/helm/base_vulnerability_scanning.py
> +    def validate_expected_CVEs_summaries(self, CVEs_summaries, expected_CVEs_summaries_path):
we already read from file in all of our validation against expected result, so I want to keep up the same behavior as our other validations function

2023-09-04 14:13 UTC, rcohencyberarmor commented on tests_scripts/helm/base_vulnerability_scanning.py
> +    def validate_expected_namespace_CVEs_summaries(self, CVEs_summaries, expected_CVEs_summaries_path, namespace):
look the comment above

2023-09-05 07:22 UTC, Daniel-GrunbergerCA commented on tests_scripts/kubernetes/base_k8s.py
> +        if any(isinstance(i, list) for i in CVEsSummariesKeys):
You still can make it a single list right? The fact that we need to check whether it's a list or a list of lists makes the function hard to reason about

2024-05-01 10:14 UTC, closed without merging