fix: add verification of fixed control
armosec/system-tests pull request #169
Opened 2023-09-09 13:46 UTC by alegrey91

2023-09-13 04:33 UTC, kooomix requested changes

2023-09-13 04:33 UTC, kooomix commented on infrastructure/backend_api.py
> +        return r
@alegrey91 
Not sure I understand this function, it seems like it will just raise error if there is at least 1 active AC, otherwise returns the response object.

2023-09-13 04:33 UTC, kooomix commented on tests_scripts/helm/ks_microservice.py
> +            raise Exception("Found attack chains don't match the expected ones")
@alegrey91 use assert rather than raising exceptions.
In addition - on the error message of the assert, inlcude as much information about the error (like what exactly didn't match) so it will be easier to understand where the problem is.

2023-09-13 04:33 UTC, kooomix commented on readme.md
> +| `scan_for_attack_chains_scenario_5_image`                                       | helm-chart |                                    | in-cluster kubescape, backend |
I understand you chose to no consolidate the tests?

2023-09-13 04:33 UTC, kooomix commented on tests_scripts/helm/ks_microservice.py
> +        time.sleep(120)
No need of this sleep as you have sleeps in the coming wait_for_report call.

2023-09-13 04:33 UTC, kooomix commented on tests_scripts/helm/ks_microservice.py
> +            raise Exception('attack-chain response differ from the expected one')
use assert with informative error message.

2023-09-13 04:33 UTC, kooomix commented on tests_scripts/helm/ks_microservice.py
> +        f = open(attack_chain_expected_values + '/' + test_scenario + '-fix_control.json')
- use os.path.join() to construct a path.
- use contants for filenames

2023-09-13 04:33 UTC, kooomix commented on tests_scripts/helm/ks_microservice.py
> +        fix_command= attack_chain_scenarios_path + '/' + test_scenario + '/' + 'fix_' + fix_type
* use os.path.join() to construct a path.
* use contants for filenames

2023-09-13 04:33 UTC, kooomix commented on tests_scripts/helm/ks_microservice.py
> +        fix_type = self.test_obj[("fix_object", None)]
what if fix_object in None?

2023-09-13 04:33 UTC, kooomix commented on tests_scripts/helm/ks_microservice.py
> +            )
Why not using the posture/scan api? (which is the one called from the UI when clicking "scan all".

2023-09-13 04:33 UTC, kooomix commented on configurations/attack-chains-test-env/attack-chain-1-1/fix_image
> +kubectl patch deployment wordpress -n default --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"wordpress:6.3.1-php8.2"}]'
* why not use the existing kubectl object for such operations?
* It could be generalised to accept parameters for re-use.
* the actual parameters should be sent to the test as configurations, so it will be easy to reuse the same test flow for different configurations.

2023-09-13 04:33 UTC, kooomix commented on configurations/attack-chains-test-env/attack-chain-1-1/fix_control
> +kubectl delete -n default ingress wordpress-ingress
* why not use the existing kubectl object for such operations?
* It could be generalised to accept parameters for re-use.
* the actual parameters should be sent to the test as configurations, so it will be easy to reuse the same test flow for different configurations.

2023-09-13 09:10 UTC, kooomix commented on infrastructure/backend_api.py
> +        return r
So it should be named to something like "has_active_attack_chains" and return true/false while the caller should handle the result.

But then, not sure you even need specific function - you can just check the result of self.get_attack_chains(cluster_name)

2023-09-13 11:40 UTC, alegrey91 commented on infrastructure/backend_api.py
> +        return r
yeah, got your point. I'm going to change it as you described.

2023-09-13 12:11 UTC, alegrey91 commented on infrastructure/backend_api.py
> +        return r
sorry, now I remember why I implemented it like so.
the reason is that we use these functions (`get_fixed_attack_chains_list`, `get_attack_chains_list`) in `wait_for_report`. so, I don't want to "exit" from `wait_for_report` until the conditions are met. We can't separate the functions. Do you agree with this? Am I missing something?

2023-09-13 13:20 UTC, alegrey91 commented on configurations/attack-chains-test-env/attack-chain-1-1/fix_control
> +kubectl delete -n default ingress wordpress-ingress
I would keep it separate from the test. It is useful to set up the environment and do some manual tests without the test suite. Hope you can get my point on this.

2023-09-13 13:23 UTC, alegrey91 commented on tests_scripts/helm/ks_microservice.py
> +            )
this function does what we need. It uses `/api/v1/posture/scan` under the hood.

2023-09-13 13:25 UTC, alegrey91 commented on tests_scripts/helm/ks_microservice.py
> +        fix_type = self.test_obj[("fix_object", None)]
should we set a default value?

2023-09-13 13:26 UTC, alegrey91 commented on tests_scripts/helm/ks_microservice.py
> +        fix_type = self.test_obj[("fix_object", None)]
let's set `control` as default in case

2023-09-13 13:45 UTC, alegrey91 commented on readme.md
> +| `scan_for_attack_chains_scenario_5_image`                                       | helm-chart |                                    | in-cluster kubescape, backend |
what do you mean?
these scenarios are used to test the different use cases we have for now.
more scenarios are coming in another PR, but for now, I would release a stable test flow.
does it look good for you?

2023-09-13 13:45 UTC, alegrey91 commented on tests_scripts/helm/ks_microservice.py
> +        time.sleep(120)
removed

2023-09-14 04:11 UTC, kooomix commented on infrastructure/backend_api.py
> +        return r
in the `wait_for_report` function you can define expected responses. You want to wait until it returns true or timeout.
In any case, the name of the function doesn't fit it's purpose, and I still think it should return true/false or maybe even not needed as you can just use ` r = self.get_attack_chains(cluster_name) `and assert on the response.

2023-09-14 04:14 UTC, kooomix commented on readme.md
> +| `scan_for_attack_chains_scenario_5_image`                                       | helm-chart |                                    | in-cluster kubescape, backend |
We have discussed of the option to combine the test with more attack chains fitting covering multiple scenarios to avoid from having to create a lot of specific tests.

2023-09-14 04:19 UTC, kooomix requested changes

2023-09-14 04:19 UTC, kooomix commented on tests_scripts/helm/ks_microservice.py
> +            )
@alegrey91 - right, but you are not testing the kubescape job request, you test to attack chains so you should work with the posture/scan directly (imagine there is a problem with the `_kubescape_job_request` function, the test might fail for reasons not related with ACs)

2023-09-15 08:42 UTC, alegrey91 commented on infrastructure/backend_api.py
> +        return r
I took a deep look over the other functions to understand if I was missing something.
So, if we use `get_attack_chains` in the `wait_for_report`:
```
r, t = self.wait_for_report(
            self.backend.get_attack_chains, 
            timeout=600, 
            current_datetime=current_datetime,
            cluster_name=cluster
            )
```
and then we `assert` the response, we are invalidating the `wait_for_report` function. We should "exit" the function only when a valid result (asserted) has been found. This way, we only retrieve something "raw" from the backend. What I wanted to obtain was a valid response that doesn't need to be asserted after the `wait_for_report` function. Even because, if the response is not valid, then we have to retrieve it again.
Other functions are doing something similar:
* `get_vuln_scan_cronjob_list`
* `get_scan_results_sum_summary`
* `get_image_scan_stats`
They are all getting the response, validating it, raising an `Exception` in case it's not valid, and finally returning it.

2023-09-15 09:08 UTC, kooomix commented on infrastructure/backend_api.py
> +        return r
Ok, I got you.

Let's just rename the function to something more suitable like has_active_attack_chains (and then you expect the number of results to be 0).

2023-09-18 05:01 UTC, kooomix requested changes

2023-09-18 05:01 UTC, kooomix commented on infrastructure/backend_api.py
> +        return r
please rename function to has_active_attack_chains and fix function accordingly.
(if value == 0 it doesn't really mean it has fixed attack chains, it just means there are no active ones.)

2023-09-18 07:16 UTC, kooomix approved these changes

2023-09-18 10:31 UTC, kooomix approved these changes

2023-09-18 10:37 UTC, merged