test: add attack chain test scenarios
armosec/system-tests pull request #177
Opened 2023-09-20 07:51 UTC by alegrey91

## PR Type:
Tests

___
## PR Description:
This PR introduces new attack chain test scenarios to the Jenkins pipeline. The new tests are designed to enhance the security testing capabilities of the system.

___
## PR Main Files Walkthrough:
`jenkins_files/Jenkinsfile-helm-ks-be.groovy`: Four new test scenarios were added to the Jenkinsfile. These tests include "scan_for_attack_chains_scenario_5_fix_control", "scan_for_attack_chains_scenario_5_fix_control_no_relevancy", "scan_for_attack_chains_scenario_alpine_fix_control", and "scan_for_attack_chains_scenario_alpine_fix_image_no_relevancy".

2023-09-20 11:23 UTC, kooomix requested changes

2023-09-20 11:23 UTC, kooomix commented on jenkins_files/Jenkinsfile-helm-ks-be.groovy
We still not ready to merge it.
And also, only the "no_relevancy" are relevant for henkins.

2023-09-28 08:56 UTC, yuleib approved these changes

2023-09-28 08:56 UTC, yuleib commented on jenkins_files/Jenkinsfile-helm-ks-be-test.groovy
> +            "scan_for_attack_chains_scenario_5_fix_control_no_relevancy":    ["CA-AWS-DEV-JENKINS-EC2-FLEET-X-LARGE",  "k8s"],
is the comma needed here?

2023-09-28 09:02 UTC, alegrey91 commented on jenkins_files/Jenkinsfile-helm-ks-be-test.groovy
> +            "scan_for_attack_chains_scenario_5_fix_control_no_relevancy":    ["CA-AWS-DEV-JENKINS-EC2-FLEET-X-LARGE",  "k8s"],
not mandatory, but we can leave it

2023-09-28 09:07 UTC, merged