Frontegg env support and payment tests
armosec/system-tests pull request #37
Opened 2023-04-30 12:11 UTC by kooomix

* Added API_login classes to support frontegg authentication.
* Extended backend api object to support new tenants management.
* Support in running a test on a specific tenant.
* Support in Admin API access.
* Fixes in payment related tests.

See new backend_api docs [here](infrastructure/backendapi.md)

2023-05-01 05:37 UTC, Bezbran commented on infrastructure/backend_api.py
> +        res = self.get(self.auth_url + "/frontegg/identity/resources/users/v2/me/tenants", headers=headers)
1. let's define thi one as a const as well
2. Why not using our backend HTTP GET to  API_OPENID_CUSTOMERS API to get the same?

2023-05-01 06:53 UTC, kooomix commented on infrastructure/backend_api.py
> +        res = self.get(self.auth_url + "/frontegg/identity/resources/users/v2/me/tenants", headers=headers)
@Bezbran 

The auth retrieved from API keys auth is different than the one from login. In order to use our open id API I needed to get another auth which I preferred to avoid.

In any case, this function will become redundant once the fix in [this PR ](https://github.com/armosec/cadashboardbe/pull/346) will be approved (then I'll get the created tenantID on creation)

2023-05-01 08:11 UTC, Bezbran approved these changes

2023-05-04 06:25 UTC, yuleib commented
@kooomix - We need to know that this new pipe is working properly before merging it. 
Please creatre a branch (**NOT FORK**) in diffrent repo (which running the system-tests) and add those chnages to the flow. We need to make sure the it's not breaked.

2023-05-04 06:28 UTC, yuleib requested changes
See my comment for running sys-tests in diff. repo

2023-05-04 06:35 UTC, kooomix commented
> @kooomix - We need to know that this new pipe is working properly before merging it. Please creatre a branch (**NOT FORK**) in diffrent repo (which running the system-tests) and add those chnages to the flow. We need to make sure the it's not breaked.

No need for a different repo, I am making the test from this branch (that won't be merged until tests will pass obvisouly)

2023-05-04 06:40 UTC, yuleib commented
@kooomix - perfect! so let's make sure we are adding it as a dedicated flow to this repo once done. 
so it will be our testing env. for any chnages from now on

2023-05-04 09:44 UTC, yuleib approved these changes

2023-05-04 09:47 UTC, merged