test: host scanner system test
armosec/system-tests pull request #99
Opened 2023-06-07 14:25 UTC by alegrey91

This PR adds a dedicated test to test `host-scanner` (`:test` tag) integration with `kubescape`.

2023-06-07 16:09 UTC, kooomix requested changes

2023-06-07 17:27 UTC, alegrey91 commented on requirements.txt
> +psycopg2-binary==2.9.6
I had problems with this version using fedora 37.
Maybe we should creat a docker image to avoid this kind of issues.

2023-06-07 17:28 UTC, alegrey91 commented
@kooomix restored `requirementes.txt` as before

2023-06-08 09:30 UTC, kooomix approved these changes

2023-06-12 08:51 UTC, merged